/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export type OrderStruct = {
  orderId: BigNumberish;
  buyer: AddressLike;
  seller: AddressLike;
  underlyingName: string;
  underlyingCode: string;
  market: string;
  country: string;
  refPrice: string;
  direction: BigNumberish;
  notionalUSDT: BigNumberish;
  strikePrice: BigNumberish;
  expiryTimestamp: BigNumberish;
  premiumRate: BigNumberish;
  premiumAmount: BigNumberish;
  initialMargin: BigNumberish;
  currentMargin: BigNumberish;
  minMarginRate: BigNumberish;
  liquidationRule: BigNumberish;
  consecutiveDays: BigNumberish;
  dailyLimitPercent: BigNumberish;
  exerciseDelay: BigNumberish;
  sellerType: BigNumberish;
  designatedSeller: AddressLike;
  arbitrationWindow: BigNumberish;
  marginCallDeadline: BigNumberish;
  dividendAdjustment: boolean;
  feedRule: BigNumberish;
  status: BigNumberish;
  createdAt: BigNumberish;
  matchedAt: BigNumberish;
  settledAt: BigNumberish;
  lastFeedPrice: BigNumberish;
  dividendAmount: BigNumberish;
};

export type OrderStructOutput = [
  orderId: bigint,
  buyer: string,
  seller: string,
  underlyingName: string,
  underlyingCode: string,
  market: string,
  country: string,
  refPrice: string,
  direction: bigint,
  notionalUSDT: bigint,
  strikePrice: bigint,
  expiryTimestamp: bigint,
  premiumRate: bigint,
  premiumAmount: bigint,
  initialMargin: bigint,
  currentMargin: bigint,
  minMarginRate: bigint,
  liquidationRule: bigint,
  consecutiveDays: bigint,
  dailyLimitPercent: bigint,
  exerciseDelay: bigint,
  sellerType: bigint,
  designatedSeller: string,
  arbitrationWindow: bigint,
  marginCallDeadline: bigint,
  dividendAdjustment: boolean,
  feedRule: bigint,
  status: bigint,
  createdAt: bigint,
  matchedAt: bigint,
  settledAt: bigint,
  lastFeedPrice: bigint,
  dividendAmount: bigint
] & {
  orderId: bigint;
  buyer: string;
  seller: string;
  underlyingName: string;
  underlyingCode: string;
  market: string;
  country: string;
  refPrice: string;
  direction: bigint;
  notionalUSDT: bigint;
  strikePrice: bigint;
  expiryTimestamp: bigint;
  premiumRate: bigint;
  premiumAmount: bigint;
  initialMargin: bigint;
  currentMargin: bigint;
  minMarginRate: bigint;
  liquidationRule: bigint;
  consecutiveDays: bigint;
  dailyLimitPercent: bigint;
  exerciseDelay: bigint;
  sellerType: bigint;
  designatedSeller: string;
  arbitrationWindow: bigint;
  marginCallDeadline: bigint;
  dividendAdjustment: boolean;
  feedRule: bigint;
  status: bigint;
  createdAt: bigint;
  matchedAt: bigint;
  settledAt: bigint;
  lastFeedPrice: bigint;
  dividendAmount: bigint;
};

export type QuoteStruct = {
  quoteId: BigNumberish;
  orderId: BigNumberish;
  seller: AddressLike;
  sellerType: BigNumberish;
  premiumRate: BigNumberish;
  premiumAmount: BigNumberish;
  marginRate: BigNumberish;
  marginAmount: BigNumberish;
  liquidationRule: BigNumberish;
  consecutiveDays: BigNumberish;
  dailyLimitPercent: BigNumberish;
  createdAt: BigNumberish;
  expiresAt: BigNumberish;
  status: BigNumberish;
};

export type QuoteStructOutput = [
  quoteId: bigint,
  orderId: bigint,
  seller: string,
  sellerType: bigint,
  premiumRate: bigint,
  premiumAmount: bigint,
  marginRate: bigint,
  marginAmount: bigint,
  liquidationRule: bigint,
  consecutiveDays: bigint,
  dailyLimitPercent: bigint,
  createdAt: bigint,
  expiresAt: bigint,
  status: bigint
] & {
  quoteId: bigint;
  orderId: bigint;
  seller: string;
  sellerType: bigint;
  premiumRate: bigint;
  premiumAmount: bigint;
  marginRate: bigint;
  marginAmount: bigint;
  liquidationRule: bigint;
  consecutiveDays: bigint;
  dailyLimitPercent: bigint;
  createdAt: bigint;
  expiresAt: bigint;
  status: bigint;
};

export interface OptionsCoreInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "FEED_PROTOCOL_ROLE"
      | "acceptQuote"
      | "acceptSellerOrder"
      | "addMargin"
      | "buyerOrders"
      | "cancelOrderDueToFeedTimeout"
      | "cancelRFQ"
      | "config"
      | "createBuyerRFQ"
      | "createSellerOrder"
      | "earlyExercise"
      | "forceLiquidate"
      | "forceLiquidateMarginCall"
      | "getBuyerOrders"
      | "getOrder"
      | "getOrdersByCountry"
      | "getOrdersByMarket"
      | "getQuotes"
      | "getRoleAdmin"
      | "getSellerOrders"
      | "grantRole"
      | "hasRole"
      | "initiateArbitration"
      | "nextOrderId"
      | "nextQuoteId"
      | "orderQuotes"
      | "orders"
      | "pause"
      | "paused"
      | "processFeedCallback"
      | "processFinalFeedResult"
      | "processInitialFeedResult"
      | "quotes"
      | "recordDividend"
      | "renounceRole"
      | "requestFeed"
      | "resolveArbitration"
      | "revokeRole"
      | "sellerOrders"
      | "setConfig"
      | "setVaultManager"
      | "settle"
      | "submitQuote"
      | "supportsInterface"
      | "triggerMarginCall"
      | "unpause"
      | "usdt"
      | "vaultManager"
      | "withdrawExcessMargin"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ArbitrationResolved"
      | "DividendRecorded"
      | "MarginCallTriggered"
      | "MarginChanged"
      | "OrderCancelled"
      | "OrderCreated"
      | "OrderLiquidated"
      | "OrderMatched"
      | "OrderSettled"
      | "OrderStatusChanged"
      | "Paused"
      | "QuoteSubmitted"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FEED_PROTOCOL_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptQuote",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "acceptSellerOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addMargin",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "buyerOrders",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelOrderDueToFeedTimeout",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelRFQ",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "config", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "createBuyerRFQ",
    values: [
      string,
      string,
      string,
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      AddressLike,
      BigNumberish,
      BigNumberish,
      boolean,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createSellerOrder",
    values: [
      string,
      string,
      string,
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      boolean,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "earlyExercise",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "forceLiquidate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "forceLiquidateMarginCall",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBuyerOrders",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOrdersByCountry",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getOrdersByMarket",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getQuotes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSellerOrders",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initiateArbitration",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextOrderId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextQuoteId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "orderQuotes",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "orders",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "processFeedCallback",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "processFinalFeedResult",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "processInitialFeedResult",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "quotes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordDividend",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestFeed",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveArbitration",
    values: [BigNumberish, BigNumberish, AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sellerOrders",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setConfig",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setVaultManager",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "settle",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitQuote",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "triggerMarginCall",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(functionFragment: "usdt", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "vaultManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawExcessMargin",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FEED_PROTOCOL_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptQuote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptSellerOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addMargin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "buyerOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelOrderDueToFeedTimeout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cancelRFQ", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "config", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createBuyerRFQ",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createSellerOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "earlyExercise",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "forceLiquidate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "forceLiquidateMarginCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBuyerOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getOrder", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getOrdersByCountry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOrdersByMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getQuotes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSellerOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initiateArbitration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextOrderId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextQuoteId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "orderQuotes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "orders", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "processFeedCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processFinalFeedResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processInitialFeedResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "quotes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordDividend",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestFeed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveArbitration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sellerOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setConfig", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setVaultManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "settle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitQuote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "triggerMarginCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "usdt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "vaultManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawExcessMargin",
    data: BytesLike
  ): Result;
}

export namespace ArbitrationResolvedEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    arbitrationId: BigNumberish,
    initiator: AddressLike,
    originalPrice: BigNumberish,
    arbitrationPrice: BigNumberish,
    resultChanged: boolean,
    initiatorReward: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    orderId: bigint,
    arbitrationId: bigint,
    initiator: string,
    originalPrice: bigint,
    arbitrationPrice: bigint,
    resultChanged: boolean,
    initiatorReward: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    orderId: bigint;
    arbitrationId: bigint;
    initiator: string;
    originalPrice: bigint;
    arbitrationPrice: bigint;
    resultChanged: boolean;
    initiatorReward: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DividendRecordedEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    dividendPerShare: BigNumberish,
    totalDividend: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    orderId: bigint,
    dividendPerShare: bigint,
    totalDividend: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    orderId: bigint;
    dividendPerShare: bigint;
    totalDividend: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarginCallTriggeredEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    seller: AddressLike,
    currentMargin: BigNumberish,
    requiredMargin: BigNumberish,
    deadline: BigNumberish
  ];
  export type OutputTuple = [
    orderId: bigint,
    seller: string,
    currentMargin: bigint,
    requiredMargin: bigint,
    deadline: bigint
  ];
  export interface OutputObject {
    orderId: bigint;
    seller: string;
    currentMargin: bigint;
    requiredMargin: bigint;
    deadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarginChangedEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    seller: AddressLike,
    oldAmount: BigNumberish,
    newAmount: BigNumberish,
    changeType: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    orderId: bigint,
    seller: string,
    oldAmount: bigint,
    newAmount: bigint,
    changeType: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    orderId: bigint;
    seller: string;
    oldAmount: bigint;
    newAmount: bigint;
    changeType: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderCancelledEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    reason: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    orderId: bigint,
    reason: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    orderId: bigint;
    reason: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderCreatedEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    creator: AddressLike,
    isBuyerOrder: boolean,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    orderId: bigint,
    creator: string,
    isBuyerOrder: boolean,
    timestamp: bigint
  ];
  export interface OutputObject {
    orderId: bigint;
    creator: string;
    isBuyerOrder: boolean;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderLiquidatedEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    beneficiary: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    orderId: bigint,
    beneficiary: string,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    orderId: bigint;
    beneficiary: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderMatchedEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    buyer: AddressLike,
    seller: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    orderId: bigint,
    buyer: string,
    seller: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    orderId: bigint;
    buyer: string;
    seller: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderSettledEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    buyerPayout: BigNumberish,
    sellerPayout: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    orderId: bigint,
    buyerPayout: bigint,
    sellerPayout: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    orderId: bigint;
    buyerPayout: bigint;
    sellerPayout: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderStatusChangedEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    oldStatus: BigNumberish,
    newStatus: BigNumberish,
    reason: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    orderId: bigint,
    oldStatus: bigint,
    newStatus: bigint,
    reason: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    orderId: bigint;
    oldStatus: bigint;
    newStatus: bigint;
    reason: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QuoteSubmittedEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    quoteId: BigNumberish,
    seller: AddressLike,
    premiumRate: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    orderId: bigint,
    quoteId: bigint,
    seller: string,
    premiumRate: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    orderId: bigint;
    quoteId: bigint;
    seller: string;
    premiumRate: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface OptionsCore extends BaseContract {
  connect(runner?: ContractRunner | null): OptionsCore;
  waitForDeployment(): Promise<this>;

  interface: OptionsCoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  FEED_PROTOCOL_ROLE: TypedContractMethod<[], [string], "view">;

  acceptQuote: TypedContractMethod<
    [quoteId: BigNumberish],
    [void],
    "nonpayable"
  >;

  acceptSellerOrder: TypedContractMethod<
    [orderId: BigNumberish],
    [void],
    "nonpayable"
  >;

  addMargin: TypedContractMethod<
    [orderId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  buyerOrders: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  cancelOrderDueToFeedTimeout: TypedContractMethod<
    [orderId: BigNumberish],
    [void],
    "nonpayable"
  >;

  cancelRFQ: TypedContractMethod<[orderId: BigNumberish], [void], "nonpayable">;

  config: TypedContractMethod<[], [string], "view">;

  createBuyerRFQ: TypedContractMethod<
    [
      underlyingName: string,
      underlyingCode: string,
      market: string,
      country: string,
      refPrice: string,
      direction: BigNumberish,
      notionalUSDT: BigNumberish,
      expiryTimestamp: BigNumberish,
      maxPremiumRate: BigNumberish,
      minMarginRate: BigNumberish,
      acceptedSellerType: BigNumberish,
      designatedSeller: AddressLike,
      arbitrationWindow: BigNumberish,
      marginCallDeadline: BigNumberish,
      dividendAdjustment: boolean,
      liquidationRule: BigNumberish,
      consecutiveDays: BigNumberish,
      dailyLimitPercent: BigNumberish,
      feedRule: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  createSellerOrder: TypedContractMethod<
    [
      underlyingName: string,
      underlyingCode: string,
      market: string,
      country: string,
      refPrice: string,
      direction: BigNumberish,
      notionalUSDT: BigNumberish,
      expiryTimestamp: BigNumberish,
      premiumRate: BigNumberish,
      marginAmount: BigNumberish,
      liquidationRule: BigNumberish,
      consecutiveDays: BigNumberish,
      dailyLimitPercent: BigNumberish,
      arbitrationWindow: BigNumberish,
      dividendAdjustment: boolean,
      exerciseDelay: BigNumberish,
      feedRule: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  earlyExercise: TypedContractMethod<
    [orderId: BigNumberish],
    [void],
    "nonpayable"
  >;

  forceLiquidate: TypedContractMethod<
    [orderId: BigNumberish],
    [void],
    "nonpayable"
  >;

  forceLiquidateMarginCall: TypedContractMethod<
    [orderId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getBuyerOrders: TypedContractMethod<[buyer: AddressLike], [bigint[]], "view">;

  getOrder: TypedContractMethod<
    [orderId: BigNumberish],
    [OrderStructOutput],
    "view"
  >;

  getOrdersByCountry: TypedContractMethod<
    [country: string],
    [bigint[]],
    "view"
  >;

  getOrdersByMarket: TypedContractMethod<[market: string], [bigint[]], "view">;

  getQuotes: TypedContractMethod<
    [orderId: BigNumberish],
    [QuoteStructOutput[]],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getSellerOrders: TypedContractMethod<
    [seller: AddressLike],
    [bigint[]],
    "view"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  initiateArbitration: TypedContractMethod<
    [orderId: BigNumberish],
    [void],
    "payable"
  >;

  nextOrderId: TypedContractMethod<[], [bigint], "view">;

  nextQuoteId: TypedContractMethod<[], [bigint], "view">;

  orderQuotes: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        quoteId: bigint;
        orderId: bigint;
        seller: string;
        sellerType: bigint;
        premiumRate: bigint;
        premiumAmount: bigint;
        marginRate: bigint;
        marginAmount: bigint;
        liquidationRule: bigint;
        consecutiveDays: bigint;
        dailyLimitPercent: bigint;
        createdAt: bigint;
        expiresAt: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  orders: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        orderId: bigint;
        buyer: string;
        seller: string;
        underlyingName: string;
        underlyingCode: string;
        market: string;
        country: string;
        refPrice: string;
        direction: bigint;
        notionalUSDT: bigint;
        strikePrice: bigint;
        expiryTimestamp: bigint;
        premiumRate: bigint;
        premiumAmount: bigint;
        initialMargin: bigint;
        currentMargin: bigint;
        minMarginRate: bigint;
        liquidationRule: bigint;
        consecutiveDays: bigint;
        dailyLimitPercent: bigint;
        exerciseDelay: bigint;
        sellerType: bigint;
        designatedSeller: string;
        arbitrationWindow: bigint;
        marginCallDeadline: bigint;
        dividendAdjustment: boolean;
        feedRule: bigint;
        status: bigint;
        createdAt: bigint;
        matchedAt: bigint;
        settledAt: bigint;
        lastFeedPrice: bigint;
        dividendAmount: bigint;
      }
    ],
    "view"
  >;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  processFeedCallback: TypedContractMethod<
    [orderId: BigNumberish, feedType: BigNumberish, finalPrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  processFinalFeedResult: TypedContractMethod<
    [orderId: BigNumberish, finalPrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  processInitialFeedResult: TypedContractMethod<
    [orderId: BigNumberish, initialPrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  quotes: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        quoteId: bigint;
        orderId: bigint;
        seller: string;
        sellerType: bigint;
        premiumRate: bigint;
        premiumAmount: bigint;
        marginRate: bigint;
        marginAmount: bigint;
        liquidationRule: bigint;
        consecutiveDays: bigint;
        dailyLimitPercent: bigint;
        createdAt: bigint;
        expiresAt: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  recordDividend: TypedContractMethod<
    [orderId: BigNumberish, dividendPerShare: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  requestFeed: TypedContractMethod<
    [orderId: BigNumberish, tier: BigNumberish],
    [void],
    "payable"
  >;

  resolveArbitration: TypedContractMethod<
    [
      orderId: BigNumberish,
      arbitrationPrice: BigNumberish,
      arbitrators: AddressLike[]
    ],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  sellerOrders: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  setConfig: TypedContractMethod<[_config: AddressLike], [void], "nonpayable">;

  setVaultManager: TypedContractMethod<
    [_vaultManager: AddressLike],
    [void],
    "nonpayable"
  >;

  settle: TypedContractMethod<[orderId: BigNumberish], [void], "nonpayable">;

  submitQuote: TypedContractMethod<
    [
      orderId: BigNumberish,
      premiumRate: BigNumberish,
      marginRate: BigNumberish,
      liquidationRule: BigNumberish,
      consecutiveDays: BigNumberish,
      dailyLimitPercent: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  triggerMarginCall: TypedContractMethod<
    [orderId: BigNumberish, isCrypto: boolean],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  usdt: TypedContractMethod<[], [string], "view">;

  vaultManager: TypedContractMethod<[], [string], "view">;

  withdrawExcessMargin: TypedContractMethod<
    [orderId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "FEED_PROTOCOL_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "acceptQuote"
  ): TypedContractMethod<[quoteId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "acceptSellerOrder"
  ): TypedContractMethod<[orderId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addMargin"
  ): TypedContractMethod<
    [orderId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "buyerOrders"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "cancelOrderDueToFeedTimeout"
  ): TypedContractMethod<[orderId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelRFQ"
  ): TypedContractMethod<[orderId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "config"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createBuyerRFQ"
  ): TypedContractMethod<
    [
      underlyingName: string,
      underlyingCode: string,
      market: string,
      country: string,
      refPrice: string,
      direction: BigNumberish,
      notionalUSDT: BigNumberish,
      expiryTimestamp: BigNumberish,
      maxPremiumRate: BigNumberish,
      minMarginRate: BigNumberish,
      acceptedSellerType: BigNumberish,
      designatedSeller: AddressLike,
      arbitrationWindow: BigNumberish,
      marginCallDeadline: BigNumberish,
      dividendAdjustment: boolean,
      liquidationRule: BigNumberish,
      consecutiveDays: BigNumberish,
      dailyLimitPercent: BigNumberish,
      feedRule: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createSellerOrder"
  ): TypedContractMethod<
    [
      underlyingName: string,
      underlyingCode: string,
      market: string,
      country: string,
      refPrice: string,
      direction: BigNumberish,
      notionalUSDT: BigNumberish,
      expiryTimestamp: BigNumberish,
      premiumRate: BigNumberish,
      marginAmount: BigNumberish,
      liquidationRule: BigNumberish,
      consecutiveDays: BigNumberish,
      dailyLimitPercent: BigNumberish,
      arbitrationWindow: BigNumberish,
      dividendAdjustment: boolean,
      exerciseDelay: BigNumberish,
      feedRule: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "earlyExercise"
  ): TypedContractMethod<[orderId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "forceLiquidate"
  ): TypedContractMethod<[orderId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "forceLiquidateMarginCall"
  ): TypedContractMethod<[orderId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getBuyerOrders"
  ): TypedContractMethod<[buyer: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getOrder"
  ): TypedContractMethod<[orderId: BigNumberish], [OrderStructOutput], "view">;
  getFunction(
    nameOrSignature: "getOrdersByCountry"
  ): TypedContractMethod<[country: string], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getOrdersByMarket"
  ): TypedContractMethod<[market: string], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getQuotes"
  ): TypedContractMethod<
    [orderId: BigNumberish],
    [QuoteStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getSellerOrders"
  ): TypedContractMethod<[seller: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "initiateArbitration"
  ): TypedContractMethod<[orderId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "nextOrderId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextQuoteId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "orderQuotes"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        quoteId: bigint;
        orderId: bigint;
        seller: string;
        sellerType: bigint;
        premiumRate: bigint;
        premiumAmount: bigint;
        marginRate: bigint;
        marginAmount: bigint;
        liquidationRule: bigint;
        consecutiveDays: bigint;
        dailyLimitPercent: bigint;
        createdAt: bigint;
        expiresAt: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "orders"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        orderId: bigint;
        buyer: string;
        seller: string;
        underlyingName: string;
        underlyingCode: string;
        market: string;
        country: string;
        refPrice: string;
        direction: bigint;
        notionalUSDT: bigint;
        strikePrice: bigint;
        expiryTimestamp: bigint;
        premiumRate: bigint;
        premiumAmount: bigint;
        initialMargin: bigint;
        currentMargin: bigint;
        minMarginRate: bigint;
        liquidationRule: bigint;
        consecutiveDays: bigint;
        dailyLimitPercent: bigint;
        exerciseDelay: bigint;
        sellerType: bigint;
        designatedSeller: string;
        arbitrationWindow: bigint;
        marginCallDeadline: bigint;
        dividendAdjustment: boolean;
        feedRule: bigint;
        status: bigint;
        createdAt: bigint;
        matchedAt: bigint;
        settledAt: bigint;
        lastFeedPrice: bigint;
        dividendAmount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "processFeedCallback"
  ): TypedContractMethod<
    [orderId: BigNumberish, feedType: BigNumberish, finalPrice: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "processFinalFeedResult"
  ): TypedContractMethod<
    [orderId: BigNumberish, finalPrice: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "processInitialFeedResult"
  ): TypedContractMethod<
    [orderId: BigNumberish, initialPrice: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "quotes"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        quoteId: bigint;
        orderId: bigint;
        seller: string;
        sellerType: bigint;
        premiumRate: bigint;
        premiumAmount: bigint;
        marginRate: bigint;
        marginAmount: bigint;
        liquidationRule: bigint;
        consecutiveDays: bigint;
        dailyLimitPercent: bigint;
        createdAt: bigint;
        expiresAt: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "recordDividend"
  ): TypedContractMethod<
    [orderId: BigNumberish, dividendPerShare: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestFeed"
  ): TypedContractMethod<
    [orderId: BigNumberish, tier: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "resolveArbitration"
  ): TypedContractMethod<
    [
      orderId: BigNumberish,
      arbitrationPrice: BigNumberish,
      arbitrators: AddressLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sellerOrders"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "setConfig"
  ): TypedContractMethod<[_config: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setVaultManager"
  ): TypedContractMethod<[_vaultManager: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "settle"
  ): TypedContractMethod<[orderId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitQuote"
  ): TypedContractMethod<
    [
      orderId: BigNumberish,
      premiumRate: BigNumberish,
      marginRate: BigNumberish,
      liquidationRule: BigNumberish,
      consecutiveDays: BigNumberish,
      dailyLimitPercent: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "triggerMarginCall"
  ): TypedContractMethod<
    [orderId: BigNumberish, isCrypto: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdt"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "vaultManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdrawExcessMargin"
  ): TypedContractMethod<
    [orderId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ArbitrationResolved"
  ): TypedContractEvent<
    ArbitrationResolvedEvent.InputTuple,
    ArbitrationResolvedEvent.OutputTuple,
    ArbitrationResolvedEvent.OutputObject
  >;
  getEvent(
    key: "DividendRecorded"
  ): TypedContractEvent<
    DividendRecordedEvent.InputTuple,
    DividendRecordedEvent.OutputTuple,
    DividendRecordedEvent.OutputObject
  >;
  getEvent(
    key: "MarginCallTriggered"
  ): TypedContractEvent<
    MarginCallTriggeredEvent.InputTuple,
    MarginCallTriggeredEvent.OutputTuple,
    MarginCallTriggeredEvent.OutputObject
  >;
  getEvent(
    key: "MarginChanged"
  ): TypedContractEvent<
    MarginChangedEvent.InputTuple,
    MarginChangedEvent.OutputTuple,
    MarginChangedEvent.OutputObject
  >;
  getEvent(
    key: "OrderCancelled"
  ): TypedContractEvent<
    OrderCancelledEvent.InputTuple,
    OrderCancelledEvent.OutputTuple,
    OrderCancelledEvent.OutputObject
  >;
  getEvent(
    key: "OrderCreated"
  ): TypedContractEvent<
    OrderCreatedEvent.InputTuple,
    OrderCreatedEvent.OutputTuple,
    OrderCreatedEvent.OutputObject
  >;
  getEvent(
    key: "OrderLiquidated"
  ): TypedContractEvent<
    OrderLiquidatedEvent.InputTuple,
    OrderLiquidatedEvent.OutputTuple,
    OrderLiquidatedEvent.OutputObject
  >;
  getEvent(
    key: "OrderMatched"
  ): TypedContractEvent<
    OrderMatchedEvent.InputTuple,
    OrderMatchedEvent.OutputTuple,
    OrderMatchedEvent.OutputObject
  >;
  getEvent(
    key: "OrderSettled"
  ): TypedContractEvent<
    OrderSettledEvent.InputTuple,
    OrderSettledEvent.OutputTuple,
    OrderSettledEvent.OutputObject
  >;
  getEvent(
    key: "OrderStatusChanged"
  ): TypedContractEvent<
    OrderStatusChangedEvent.InputTuple,
    OrderStatusChangedEvent.OutputTuple,
    OrderStatusChangedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "QuoteSubmitted"
  ): TypedContractEvent<
    QuoteSubmittedEvent.InputTuple,
    QuoteSubmittedEvent.OutputTuple,
    QuoteSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "ArbitrationResolved(uint256,uint256,address,uint256,uint256,bool,uint256,uint256)": TypedContractEvent<
      ArbitrationResolvedEvent.InputTuple,
      ArbitrationResolvedEvent.OutputTuple,
      ArbitrationResolvedEvent.OutputObject
    >;
    ArbitrationResolved: TypedContractEvent<
      ArbitrationResolvedEvent.InputTuple,
      ArbitrationResolvedEvent.OutputTuple,
      ArbitrationResolvedEvent.OutputObject
    >;

    "DividendRecorded(uint256,uint256,uint256,uint256)": TypedContractEvent<
      DividendRecordedEvent.InputTuple,
      DividendRecordedEvent.OutputTuple,
      DividendRecordedEvent.OutputObject
    >;
    DividendRecorded: TypedContractEvent<
      DividendRecordedEvent.InputTuple,
      DividendRecordedEvent.OutputTuple,
      DividendRecordedEvent.OutputObject
    >;

    "MarginCallTriggered(uint256,address,uint256,uint256,uint256)": TypedContractEvent<
      MarginCallTriggeredEvent.InputTuple,
      MarginCallTriggeredEvent.OutputTuple,
      MarginCallTriggeredEvent.OutputObject
    >;
    MarginCallTriggered: TypedContractEvent<
      MarginCallTriggeredEvent.InputTuple,
      MarginCallTriggeredEvent.OutputTuple,
      MarginCallTriggeredEvent.OutputObject
    >;

    "MarginChanged(uint256,address,uint256,uint256,string,uint256)": TypedContractEvent<
      MarginChangedEvent.InputTuple,
      MarginChangedEvent.OutputTuple,
      MarginChangedEvent.OutputObject
    >;
    MarginChanged: TypedContractEvent<
      MarginChangedEvent.InputTuple,
      MarginChangedEvent.OutputTuple,
      MarginChangedEvent.OutputObject
    >;

    "OrderCancelled(uint256,string,uint256)": TypedContractEvent<
      OrderCancelledEvent.InputTuple,
      OrderCancelledEvent.OutputTuple,
      OrderCancelledEvent.OutputObject
    >;
    OrderCancelled: TypedContractEvent<
      OrderCancelledEvent.InputTuple,
      OrderCancelledEvent.OutputTuple,
      OrderCancelledEvent.OutputObject
    >;

    "OrderCreated(uint256,address,bool,uint256)": TypedContractEvent<
      OrderCreatedEvent.InputTuple,
      OrderCreatedEvent.OutputTuple,
      OrderCreatedEvent.OutputObject
    >;
    OrderCreated: TypedContractEvent<
      OrderCreatedEvent.InputTuple,
      OrderCreatedEvent.OutputTuple,
      OrderCreatedEvent.OutputObject
    >;

    "OrderLiquidated(uint256,address,uint256,uint256)": TypedContractEvent<
      OrderLiquidatedEvent.InputTuple,
      OrderLiquidatedEvent.OutputTuple,
      OrderLiquidatedEvent.OutputObject
    >;
    OrderLiquidated: TypedContractEvent<
      OrderLiquidatedEvent.InputTuple,
      OrderLiquidatedEvent.OutputTuple,
      OrderLiquidatedEvent.OutputObject
    >;

    "OrderMatched(uint256,address,address,uint256)": TypedContractEvent<
      OrderMatchedEvent.InputTuple,
      OrderMatchedEvent.OutputTuple,
      OrderMatchedEvent.OutputObject
    >;
    OrderMatched: TypedContractEvent<
      OrderMatchedEvent.InputTuple,
      OrderMatchedEvent.OutputTuple,
      OrderMatchedEvent.OutputObject
    >;

    "OrderSettled(uint256,uint256,uint256,uint256)": TypedContractEvent<
      OrderSettledEvent.InputTuple,
      OrderSettledEvent.OutputTuple,
      OrderSettledEvent.OutputObject
    >;
    OrderSettled: TypedContractEvent<
      OrderSettledEvent.InputTuple,
      OrderSettledEvent.OutputTuple,
      OrderSettledEvent.OutputObject
    >;

    "OrderStatusChanged(uint256,uint8,uint8,string,uint256)": TypedContractEvent<
      OrderStatusChangedEvent.InputTuple,
      OrderStatusChangedEvent.OutputTuple,
      OrderStatusChangedEvent.OutputObject
    >;
    OrderStatusChanged: TypedContractEvent<
      OrderStatusChangedEvent.InputTuple,
      OrderStatusChangedEvent.OutputTuple,
      OrderStatusChangedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "QuoteSubmitted(uint256,uint256,address,uint256,uint256)": TypedContractEvent<
      QuoteSubmittedEvent.InputTuple,
      QuoteSubmittedEvent.OutputTuple,
      QuoteSubmittedEvent.OutputObject
    >;
    QuoteSubmitted: TypedContractEvent<
      QuoteSubmittedEvent.InputTuple,
      QuoteSubmittedEvent.OutputTuple,
      QuoteSubmittedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
