/**
 * Contract ABIs - Auto-generated from Hardhat compilation artifacts
 * Generated at: 2026-03-19T01:55:13.957Z
 * DO NOT EDIT MANUALLY - run gen_abis.js to regenerate
 */

// OptionsCore ABI
export const OptionsCoreABI = [
    // Functions
    'function DEFAULT_ADMIN_ROLE() view returns (bytes32)',
    'function FEED_PROTOCOL_ROLE() view returns (bytes32)',
    'function SETTLEMENT_ROLE() view returns (bytes32)',
    'function acceptQuote(uint256 quoteId)',
    'function acceptSellerOrder(uint256 orderId)',
    'function buyerOrders(address, uint256) view returns (uint256)',
    'function cancelRFQ(uint256 orderId)',
    'function cancelRFQDueToTimeout(uint256 orderId)',
    'function config() view returns (address)',
    'function createBuyerRFQ(string underlyingName, string underlyingCode, string market, string country, string refPrice, uint8 direction, uint256 notionalUSDT, uint256 expiryTimestamp, uint256 maxPremiumRate, uint256 minMarginRate, uint8 acceptedSellerType, address designatedSeller, uint256 arbitrationWindow, uint256 marginCallDeadline, bool dividendAdjustment, uint8 liquidationRule, uint8 consecutiveDays, uint8 dailyLimitPercent, uint8 feedRule) returns (uint256 orderId)',
    'function createSellerOrder(string underlyingName, string underlyingCode, string market, string country, string refPrice, uint8 direction, uint256 notionalUSDT, uint256 expiryTimestamp, uint256 premiumRate, uint256 marginAmount, uint8 liquidationRule, uint8 consecutiveDays, uint8 dailyLimitPercent, uint256 arbitrationWindow, bool dividendAdjustment, uint8 exerciseDelay, uint8 feedRule) returns (uint256 orderId)',
    'function getBuyerOrders(address buyer) view returns (uint256[])',
    'function getOrder(uint256 orderId) view returns (tuple(uint256 orderId, address buyer, address seller, string underlyingName, string underlyingCode, string market, string country, string refPrice, uint8 direction, uint256 notionalUSDT, uint256 strikePrice, uint256 expiryTimestamp, uint256 premiumRate, uint256 premiumAmount, uint256 initialMargin, uint256 currentMargin, uint256 minMarginRate, uint256 maxPremiumRate, uint8 liquidationRule, uint8 consecutiveDays, uint8 dailyLimitPercent, uint8 exerciseDelay, uint8 sellerType, address designatedSeller, uint256 arbitrationWindow, uint256 marginCallDeadline, bool dividendAdjustment, uint8 feedRule, uint8 status, uint256 createdAt, uint256 matchedAt, uint256 settledAt, uint256 lastFeedPrice, uint256 dividendAmount))',
    'function getOrdersByCountry(string country) view returns (uint256[])',
    'function getOrdersByMarket(string market) view returns (uint256[])',
    'function getQuotes(uint256 orderId) view returns (tuple(uint256 quoteId, uint256 orderId, address seller, uint8 sellerType, uint256 premiumRate, uint256 premiumAmount, uint256 marginRate, uint256 marginAmount, uint8 liquidationRule, uint8 consecutiveDays, uint8 dailyLimitPercent, uint256 createdAt, uint256 expiresAt, uint8 status)[])',
    'function getRoleAdmin(bytes32 role) view returns (bytes32)',
    'function getSellerOrders(address seller) view returns (uint256[])',
    'function grantRole(bytes32 role, address account)',
    'function hasRole(bytes32 role, address account) view returns (bool)',
    'function nextOrderId() view returns (uint256)',
    'function nextQuoteId() view returns (uint256)',
    'function orderQuotes(uint256, uint256) view returns (uint256 quoteId, uint256 orderId, address seller, uint8 sellerType, uint256 premiumRate, uint256 premiumAmount, uint256 marginRate, uint256 marginAmount, uint8 liquidationRule, uint8 consecutiveDays, uint8 dailyLimitPercent, uint256 createdAt, uint256 expiresAt, uint8 status)',
    'function orders(uint256) view returns (uint256 orderId, address buyer, address seller, string underlyingName, string underlyingCode, string market, string country, string refPrice, uint8 direction, uint256 notionalUSDT, uint256 strikePrice, uint256 expiryTimestamp, uint256 premiumRate, uint256 premiumAmount, uint256 initialMargin, uint256 currentMargin, uint256 minMarginRate, uint256 maxPremiumRate, uint8 liquidationRule, uint8 consecutiveDays, uint8 dailyLimitPercent, uint8 exerciseDelay, uint8 sellerType, address designatedSeller, uint256 arbitrationWindow, uint256 marginCallDeadline, bool dividendAdjustment, uint8 feedRule, uint8 status, uint256 createdAt, uint256 matchedAt, uint256 settledAt, uint256 lastFeedPrice, uint256 dividendAmount)',
    'function pause()',
    'function paused() view returns (bool)',
    'function processFeedCallback(uint256 orderId, uint8 feedType, uint256 finalPrice)',
    'function processFinalFeedResult(uint256 orderId, uint256 finalPrice)',
    'function processInitialFeedResult(uint256 orderId, uint256 initialPrice)',
    'function quotes(uint256) view returns (uint256 quoteId, uint256 orderId, address seller, uint8 sellerType, uint256 premiumRate, uint256 premiumAmount, uint256 marginRate, uint256 marginAmount, uint8 liquidationRule, uint8 consecutiveDays, uint8 dailyLimitPercent, uint256 createdAt, uint256 expiresAt, uint8 status)',
    'function renounceRole(bytes32 role, address callerConfirmation)',
    'function requestFeed(uint256 orderId, uint8 tier) payable',
    'function revokeRole(bytes32 role, address account)',
    'function sellerOrders(address, uint256) view returns (uint256)',
    'function setConfig(address _config)',
    'function setVaultManager(address _vaultManager)',
    'function submitQuote(uint256 orderId, uint256 premiumRate, uint256 marginRate, uint8 liquidationRule, uint8 consecutiveDays, uint8 dailyLimitPercent) returns (uint256 quoteId)',
    'function supportsInterface(bytes4 interfaceId) view returns (bool)',
    'function unpause()',
    'function updateOrderDividend(uint256 orderId, uint256 amount)',
    'function updateOrderMargin(uint256 orderId, uint256 newMargin)',
    'function updateOrderMarginCallDeadline(uint256 orderId, uint256 deadline)',
    'function updateOrderPrice(uint256 orderId, uint256 newPrice)',
    'function updateOrderSettledAt(uint256 orderId, uint256 timestamp)',
    'function updateOrderStatus(uint256 orderId, uint8 newStatus)',
    'function updateOrderStrikePrice(uint256 orderId, uint256 price)',
    'function usdt() view returns (address)',
    'function vaultManager() view returns (address)',
    // Events
    'event FeedRequestEmitted(uint256 indexed orderId, string underlyingCode, string market, string country, uint8 feedType, uint8 tier, address indexed requester, uint256 notionalAmount, uint256 timestamp)',
    'event OrderCancelled(uint256 indexed orderId, string reason, uint256 timestamp)',
    'event OrderCreated(uint256 indexed orderId, address indexed creator, bool isBuyerOrder, uint256 timestamp)',
    'event OrderMatched(uint256 indexed orderId, address indexed buyer, address indexed seller, uint256 timestamp)',
    'event OrderStatusChanged(uint256 indexed orderId, uint8 oldStatus, uint8 newStatus, string reason, uint256 timestamp)',
    'event Paused(address account)',
    'event QuoteMarginRefunded(uint256 indexed orderId, uint256 indexed quoteId, address indexed seller, uint256 amount, uint256 timestamp)',
    'event QuoteSubmitted(uint256 indexed orderId, uint256 indexed quoteId, address indexed seller, uint256 premiumRate, uint256 timestamp)',
    'event RoleAdminChanged(bytes32 indexed role, bytes32 indexed previousAdminRole, bytes32 indexed newAdminRole)',
    'event RoleGranted(bytes32 indexed role, address indexed account, address indexed sender)',
    'event RoleRevoked(bytes32 indexed role, address indexed account, address indexed sender)',
    'event Unpaused(address account)',
] as const;

// OptionsSettlement ABI
export const OptionsSettlementABI = [
    // Functions
    'function DEFAULT_ADMIN_ROLE() view returns (bytes32)',
    'function addMargin(uint256 orderId, uint256 amount)',
    'function arbitrationInitiator(uint256) view returns (address)',
    'function cancelOrderDueFinalFeedTimeout(uint256 orderId)',
    'function cancelOrderDueToFeedTimeout(uint256 orderId)',
    'function config() view returns (address)',
    'function earlyExercise(uint256 orderId)',
    'function forceLiquidate(uint256 orderId)',
    'function forceLiquidateMarginCall(uint256 orderId)',
    'function getRoleAdmin(bytes32 role) view returns (bytes32)',
    'function grantRole(bytes32 role, address account)',
    'function hasRole(bytes32 role, address account) view returns (bool)',
    'function initiateArbitration(uint256 orderId) payable',
    'function optionsCore() view returns (address)',
    'function pause()',
    'function paused() view returns (bool)',
    'function recordDividend(uint256 orderId, uint256 dividendPerShare)',
    'function renounceRole(bytes32 role, address callerConfirmation)',
    'function resolveArbitration(uint256 orderId, uint256 arbitrationPrice, address[] arbitrators)',
    'function revokeRole(bytes32 role, address account)',
    'function setConfig(address _config)',
    'function setOptionsCore(address _optionsCore)',
    'function settle(uint256 orderId)',
    'function supportsInterface(bytes4 interfaceId) view returns (bool)',
    'function triggerMarginCall(uint256 orderId, bool isCrypto)',
    'function unpause()',
    'function usdt() view returns (address)',
    'function vaultManager() view returns (address)',
    'function withdrawExcessMargin(uint256 orderId, uint256 amount)',
    // Events
    'event ArbitrationResolved(uint256 indexed orderId, uint256 indexed arbitrationId, address initiator, uint256 originalPrice, uint256 arbitrationPrice, bool resultChanged, uint256 initiatorReward, uint256 timestamp)',
    'event DividendRecorded(uint256 indexed orderId, uint256 dividendPerShare, uint256 totalDividend, uint256 timestamp)',
    'event MarginCallTriggered(uint256 indexed orderId, address indexed seller, uint256 currentMargin, uint256 requiredMargin, uint256 deadline)',
    'event MarginChanged(uint256 indexed orderId, address indexed seller, uint256 oldAmount, uint256 newAmount, string changeType, uint256 timestamp)',
    'event OrderCancelled(uint256 indexed orderId, string reason, uint256 timestamp)',
    'event OrderLiquidated(uint256 indexed orderId, address beneficiary, uint256 amount, uint256 timestamp)',
    'event OrderSettled(uint256 indexed orderId, uint256 buyerPayout, uint256 sellerPayout, uint256 timestamp)',
    'event OrderStatusChanged(uint256 indexed orderId, uint8 oldStatus, uint8 newStatus, string reason, uint256 timestamp)',
    'event Paused(address account)',
    'event RoleAdminChanged(bytes32 indexed role, bytes32 indexed previousAdminRole, bytes32 indexed newAdminRole)',
    'event RoleGranted(bytes32 indexed role, address indexed account, address indexed sender)',
    'event RoleRevoked(bytes32 indexed role, address indexed account, address indexed sender)',
    'event Unpaused(address account)',
] as const;

// FeedProtocol ABI
export const FeedProtocolABI = [
    // Functions
    'function DEFAULT_ADMIN_ROLE() view returns (bytes32)',
    'function FEED_OPERATOR_ROLE() view returns (bytes32)',
    'function PROTOCOL_ROLE() view returns (bytes32)',
    'function SENIOR_FEEDER_ROLE() view returns (bytes32)',
    'function addStake(uint256 amount)',
    'function blacklistFeeder(address feeder, string reason)',
    'function config() view returns (address)',
    'function createFeedRequest(uint256 orderId, uint8 feedType, uint8 tier) payable returns (uint256 requestId)',
    'function feedRequests(uint256) view returns (uint256 requestId, uint256 orderId, uint8 feedType, uint8 tier, uint256 deadline, uint256 createdAt, uint256 totalFeeders, uint256 submittedCount, uint256 finalPrice, bool finalized)',
    'function feederList(uint256) view returns (address)',
    'function feederSelector() view returns (address)',
    'function feeders(address) view returns (address feederAddress, uint256 stakedAmount, uint256 completedFeeds, uint256 rejectedFeeds, uint256 registeredAt, bool isActive, bool isBlacklisted)',
    'function finalizeFeed(uint256 requestId) returns (uint256 finalPrice)',
    'function getActiveFeeders() view returns (address[])',
    'function getAllFeedRequests(uint256 offset, uint256 limit) view returns (tuple(uint256 requestId, uint256 orderId, uint8 feedType, uint8 tier, uint256 deadline, uint256 createdAt, uint256 totalFeeders, uint256 submittedCount, uint256 finalPrice, bool finalized)[])',
    'function getFeedFee(uint8 tier) view returns (uint256)',
    'function getFeedRequest(uint256 requestId) view returns (tuple(uint256 requestId, uint256 orderId, uint8 feedType, uint8 tier, uint256 deadline, uint256 createdAt, uint256 totalFeeders, uint256 submittedCount, uint256 finalPrice, bool finalized))',
    'function getFeeder(address feeder) view returns (tuple(address feederAddress, uint256 stakedAmount, uint256 completedFeeds, uint256 rejectedFeeds, uint256 registeredAt, bool isActive, bool isBlacklisted))',
    'function getFeederCount() view returns (uint256)',
    'function getMaliciousReport(uint256 reportId) view returns (tuple(uint256 reportId, address reporter, address reportedFeeder, uint256 requestId, string evidence, uint256 reportedAt, bool processed, bool confirmed))',
    'function getOrderFeedRequests(uint256 orderId) view returns (uint256[])',
    'function getPendingRequests() view returns (tuple(uint256 requestId, uint256 orderId, uint8 feedType, uint8 tier, uint256 deadline, uint256 createdAt, uint256 totalFeeders, uint256 submittedCount, uint256 finalPrice, bool finalized)[])',
    'function getRoleAdmin(bytes32 role) view returns (bytes32)',
    'function getSubmissions(uint256 requestId) view returns (tuple(address feeder, uint256 price, uint256 timestamp, bool isValid)[])',
    'function getTotalRequestCount() view returns (uint256)',
    'function grantProtocolRole(address protocol)',
    'function grantRole(bytes32 role, address account)',
    'function grantSeniorFeederRole(address feeder)',
    'function hasRole(bytes32 role, address account) view returns (bool)',
    'function hasSubmitted(uint256, address) view returns (bool)',
    'function maliciousReports(uint256) view returns (uint256 reportId, address reporter, address reportedFeeder, uint256 requestId, string evidence, uint256 reportedAt, bool processed, bool confirmed)',
    'function nextReportId() view returns (uint256)',
    'function nextRequestId() view returns (uint256)',
    'function optionsCore() view returns (address)',
    'function orderFeedRequests(uint256, uint256) view returns (uint256)',
    'function pause()',
    'function paused() view returns (bool)',
    'function processMaliciousReport(uint256 reportId, bool confirmed, uint256 slashPercent)',
    'function registerFeeder(uint256 stakeAmount)',
    'function rejectFeed(uint256 requestId, string reason)',
    'function renounceRole(bytes32 role, address callerConfirmation)',
    'function reportMaliciousFeed(address feeder, uint256 requestId, string evidence) returns (uint256 reportId)',
    'function requestFeedPublic(uint256 orderId, uint8 feedType, uint8 tier) returns (uint256 requestId)',
    'function requestSubmissions(uint256, uint256) view returns (address feeder, uint256 price, uint256 timestamp, bool isValid)',
    'function revokeRole(bytes32 role, address account)',
    'function setConfig(address _config)',
    'function setFeederSelector(address _feederSelector)',
    'function setOptionsCore(address _optionsCore)',
    'function setTierConfig(uint8 tier, uint8 totalFeeders, uint8 effectiveFeeds, uint256 platformFee, uint256 feederReward, uint256 totalFee)',
    'function submitFeed(uint256 requestId, uint256 price)',
    'function supportsInterface(bytes4 interfaceId) view returns (bool)',
    'function tierConfigs(uint8) view returns (uint8 totalFeeders, uint8 effectiveFeeds, uint256 platformFee, uint256 feederReward, uint256 totalFee)',
    'function unpause()',
    'function usdt() view returns (address)',
    'function withdrawPlatformFees(address to)',
    'function withdrawStake(uint256 amount)',
    // Events
    'event CallbackFailed(uint256 indexed requestId, uint256 indexed orderId, string reason)',
    'event FeedFinalized(uint256 indexed requestId, uint256 finalPrice, uint256 timestamp)',
    'event FeedRejected(uint256 indexed requestId, address indexed feeder, string reason, uint256 timestamp)',
    'event FeedRequested(uint256 indexed requestId, uint256 indexed orderId, string underlyingName, string underlyingCode, string market, string country, uint8 feedType, uint8 liquidationRule, uint8 consecutiveDays, uint8 exerciseDelay, uint256 timestamp)',
    'event FeedSubmitted(uint256 indexed requestId, address indexed feeder, uint256 price, uint256 timestamp)',
    'event FeederBlacklisted(address indexed feeder, string reason, uint256 timestamp)',
    'event FeederDeactivated(address indexed feeder, string reason, uint256 timestamp)',
    'event FeederRegistered(address indexed feeder, uint256 stakedAmount, uint256 timestamp)',
    'event MaliciousFeedReported(uint256 indexed reportId, address indexed reporter, address indexed feeder, uint256 requestId, uint256 timestamp)',
    'event MaliciousReportProcessed(uint256 indexed reportId, bool confirmed, uint256 slashedAmount, uint256 timestamp)',
    'event OptionsCoreUpdated(address indexed oldAddress, address indexed newAddress, uint256 timestamp)',
    'event Paused(address account)',
    'event RewardDistributed(uint256 indexed requestId, address indexed feeder, uint256 amount, uint256 timestamp)',
    'event RoleAdminChanged(bytes32 indexed role, bytes32 indexed previousAdminRole, bytes32 indexed newAdminRole)',
    'event RoleGranted(bytes32 indexed role, address indexed account, address indexed sender)',
    'event RoleRevoked(bytes32 indexed role, address indexed account, address indexed sender)',
    'event Unpaused(address account)',
] as const;

// PointsManager ABI
export const PointsManagerABI = [
    // Functions
    'function AIRDROP_ADMIN_ROLE() view returns (bytes32)',
    'function DEFAULT_ADMIN_ROLE() view returns (bytes32)',
    'function POINTS_OPERATOR_ROLE() view returns (bytes32)',
    'function airdropCounter() view returns (uint256)',
    'function claimAirdrop()',
    'function claimedAmount(uint256, address) view returns (uint256)',
    'function config() view returns (address)',
    'function createAirdrop(uint256 totalPool, uint256 startTime, uint256 endTime)',
    'function currentAirdrop() view returns (uint256 totalPool, uint256 startTime, uint256 endTime, uint256 totalPointsSnapshot, bool isActive, uint256 airdropId)',
    'function endAirdrop()',
    'function getClaimableAirdrop(address user) view returns (uint256)',
    'function getCurrentAirdrop() view returns (tuple(uint256 totalPool, uint256 startTime, uint256 endTime, uint256 totalPointsSnapshot, bool isActive, uint256 airdropId))',
    'function getPoints(address user) view returns (uint256)',
    'function getPointsUserCount() view returns (uint256)',
    'function getRoleAdmin(bytes32 role) view returns (bytes32)',
    'function getUserPoints(address user) view returns (tuple(uint256 totalPoints, uint256 claimedPoints, uint256 availablePoints, uint256 lastUpdateTime))',
    'function grantOperatorRole(address operator)',
    'function grantRole(bytes32 role, address account)',
    'function hasClaimed(uint256, address) view returns (bool)',
    'function hasClaimedAirdrop(uint256 airdropId, address user) view returns (bool)',
    'function hasRole(bytes32 role, address account) view returns (bool)',
    'function nstToken() view returns (address)',
    'function pause()',
    'function paused() view returns (bool)',
    'function pointsUsers(uint256) view returns (address)',
    'function recordPoints(address user, uint256 feeAmount, string feeType)',
    'function renounceRole(bytes32 role, address callerConfirmation)',
    'function revokeRole(bytes32 role, address account)',
    'function setConfig(address _config)',
    'function setNSTToken(address _nstToken)',
    'function supportsInterface(bytes4 interfaceId) view returns (bool)',
    'function totalClaimedPoints() view returns (uint256)',
    'function totalPoints() view returns (uint256)',
    'function unpause()',
    'function userPoints(address) view returns (uint256 totalPoints, uint256 claimedPoints, uint256 availablePoints, uint256 lastUpdateTime)',
    'function withdrawRemainingTokens(address to)',
    // Events
    'event AirdropClaimed(address indexed user, uint256 indexed airdropId, uint256 pointsUsed, uint256 tokenAmount, uint256 timestamp)',
    'event AirdropCreated(uint256 indexed airdropId, uint256 totalPool, uint256 startTime, uint256 endTime, uint256 timestamp)',
    'event AirdropEnded(uint256 indexed airdropId, uint256 totalClaimed, uint256 timestamp)',
    'event Paused(address account)',
    'event PointsAccumulated(address indexed user, uint256 amount, string feeType, uint256 timestamp)',
    'event RoleAdminChanged(bytes32 indexed role, bytes32 indexed previousAdminRole, bytes32 indexed newAdminRole)',
    'event RoleGranted(bytes32 indexed role, address indexed account, address indexed sender)',
    'event RoleRevoked(bytes32 indexed role, address indexed account, address indexed sender)',
    'event Unpaused(address account)',
] as const;

// SeatManager ABI
export const SeatManagerABI = [
    // Functions
    'function DEFAULT_ADMIN_ROLE() view returns (bytes32)',
    'function OPTIONS_CORE_ROLE() view returns (bytes32)',
    'function SEAT_OPERATOR_ROLE() view returns (bytes32)',
    'function addDeposit(uint256 amount)',
    'function canTakeOrder(address seller, uint256 notional) view returns (bool)',
    'function config() view returns (address)',
    'function deactivateSeat(address owner, string reason)',
    'function getAllSeatOwners() view returns (address[])',
    'function getRoleAdmin(bytes32 role) view returns (bytes32)',
    'function getSeat(address owner) view returns (tuple(address owner, uint256 depositAmount, uint256 nstStaked, uint256 stakeStartTime, uint256 currentExposure, uint256 maxExposure, bool isActive))',
    'function getSeatCount() view returns (uint256)',
    'function grantOptionsCoreRole(address _optionsCore)',
    'function grantRole(bytes32 role, address account)',
    'function hasRole(bytes32 role, address account) view returns (bool)',
    'function isValidSeat(address seller) view returns (bool)',
    'function nstToken() view returns (address)',
    'function pause()',
    'function paused() view returns (bool)',
    'function reactivateSeat(address owner)',
    'function registerSeat(uint256 depositAmount)',
    'function renounceRole(bytes32 role, address callerConfirmation)',
    'function revokeRole(bytes32 role, address account)',
    'function seatOwners(uint256) view returns (address)',
    'function seats(address) view returns (address owner, uint256 depositAmount, uint256 nstStaked, uint256 stakeStartTime, uint256 currentExposure, uint256 maxExposure, bool isActive)',
    'function setConfig(address _config)',
    'function setNSTToken(address _nstToken)',
    'function setSeatParams(address seller, uint256 depositAmount, uint256 maxExposure)',
    'function stakeNST(uint256 amount)',
    'function supportsInterface(bytes4 interfaceId) view returns (bool)',
    'function unpause()',
    'function unstakeNST(uint256 amount)',
    'function updateExposure(address seller, uint256 notional, bool isAdd)',
    'function usdt() view returns (address)',
    'function withdrawDeposit(uint256 amount)',
    // Events
    'event DepositUpdated(address indexed owner, uint256 oldAmount, uint256 newAmount, uint256 timestamp)',
    'event ExposureUpdated(address indexed owner, uint256 oldExposure, uint256 newExposure, bool isIncrease, uint256 timestamp)',
    'event NSTStaked(address indexed owner, uint256 amount, uint256 timestamp)',
    'event NSTUnstaked(address indexed owner, uint256 amount, uint256 timestamp)',
    'event Paused(address account)',
    'event RoleAdminChanged(bytes32 indexed role, bytes32 indexed previousAdminRole, bytes32 indexed newAdminRole)',
    'event RoleGranted(bytes32 indexed role, address indexed account, address indexed sender)',
    'event RoleRevoked(bytes32 indexed role, address indexed account, address indexed sender)',
    'event SeatDeactivated(address indexed owner, string reason, uint256 timestamp)',
    'event SeatParamsUpdated(address indexed owner, uint256 depositAmount, uint256 maxExposure, uint256 timestamp)',
    'event SeatReactivated(address indexed owner, uint256 timestamp)',
    'event SeatRegistered(address indexed owner, uint256 depositAmount, uint256 maxExposure, uint256 timestamp)',
    'event Unpaused(address account)',
] as const;

// VaultManager ABI
export const VaultManagerABI = [
    // Functions
    'function DEFAULT_ADMIN_ROLE() view returns (bytes32)',
    'function VAULT_OPERATOR_ROLE() view returns (bytes32)',
    'function adminSetMarginBalance(address _user, address _token, uint256 _amount)',
    'function allocateProfitToSubPools(address _token, uint256 _lpAmount, uint256 _interactAmount, uint256 _donationAmount)',
    'function batchDistributeNodeRewards(address _token, address[] _recipients, uint256[] _amounts)',
    'function collectFee(address _user, address _token, uint256 _amount, string _feeType)',
    'function config() view returns (address)',
    'function depositMargin(address _user, address _token, uint256 _amount)',
    'function depositToDonationPool(address _token, uint256 _amount)',
    'function depositToInteractPool(address _token, uint256 _amount)',
    'function depositToLPPool(address _token, uint256 _amount)',
    'function distributeProfits(address _token, uint256 _amount)',
    'function donationPoolBalance(address) view returns (uint256)',
    'function getProfitPoolBalance(address _token) view returns (uint256)',
    'function getRoleAdmin(bytes32 role) view returns (bytes32)',
    'function getTotalMarginPool(address _token) view returns (uint256)',
    'function getUserMarginBalance(address _user, address _token) view returns (uint256)',
    'function grantOperatorRole(address _operator)',
    'function grantRole(bytes32 role, address account)',
    'function hasRole(bytes32 role, address account) view returns (bool)',
    'function interactPoolBalance(address) view returns (uint256)',
    'function lpPoolBalance(address) view returns (uint256)',
    'function marginPoolBalance(address) view returns (uint256)',
    'function pause()',
    'function paused() view returns (bool)',
    'function penaltyToTreasury(address _user, address _token, uint256 _amount)',
    'function profitPoolBalance(address) view returns (uint256)',
    'function refundMargin(address _seller, uint256 _amount)',
    'function refundPremium(address _buyer, uint256 _amount)',
    'function renounceRole(bytes32 role, address callerConfirmation)',
    'function revokeRole(bytes32 role, address account)',
    'function setConfig(address _config)',
    'function supportsInterface(bytes4 interfaceId) view returns (bool)',
    'function transferMargin(address _from, address _to, address _token, uint256 _amount, string _reason)',
    'function transferReward(address _recipient, uint256 _amount)',
    'function transferToFeedProtocol(address _token, uint256 _amount, address _feedProtocol)',
    'function transferToTreasury(uint256 _amount)',
    'function unpause()',
    'function userMarginBalance(address, address) view returns (uint256)',
    'function withdrawFromDonationPool(address _token, uint256 _amount, address _recipient)',
    'function withdrawFromInteractPool(address _token, uint256 _amount, address _recipient)',
    'function withdrawFromLPPool(address _token, uint256 _amount, address _recipient)',
    'function withdrawMargin(address _user, address _token, uint256 _amount)',
    // Events
    'event FeeCollected(address indexed token, uint256 amount, string feeType, uint256 timestamp)',
    'event MarginDeposited(address indexed user, address indexed token, uint256 amount, uint256 timestamp)',
    'event MarginTransferred(address indexed from, address indexed to, address indexed token, uint256 amount, string reason, uint256 timestamp)',
    'event MarginWithdrawn(address indexed user, address indexed token, uint256 amount, uint256 timestamp)',
    'event Paused(address account)',
    'event ProfitDistributed(address indexed token, uint256 amount, string poolType, uint256 timestamp)',
    'event RoleAdminChanged(bytes32 indexed role, bytes32 indexed previousAdminRole, bytes32 indexed newAdminRole)',
    'event RoleGranted(bytes32 indexed role, address indexed account, address indexed sender)',
    'event RoleRevoked(bytes32 indexed role, address indexed account, address indexed sender)',
    'event Unpaused(address account)',
] as const;

// VolumeBasedFeed ABI
export const VolumeBasedFeedABI = [
    // Functions
    'function DEFAULT_ADMIN_ROLE() view returns (bytes32)',
    'function FEEDER_ROLE() view returns (bytes32)',
    'function FEED_OPERATOR_ROLE() view returns (bytes32)',
    'function PROTOCOL_ROLE() view returns (bytes32)',
    'function approvePrice(uint256 requestId)',
    'function config() view returns (address)',
    'function getFinalPrice(uint256 requestId) view returns (uint256, bool)',
    'function getOrderVolumeRequests(uint256 orderId) view returns (uint256[])',
    'function getRejectReasonString(uint8 reason) pure returns (string)',
    'function getRequest(uint256 requestId) view returns (tuple(uint256 requestId, uint256 orderId, address seller, uint256 suggestedPrice, string priceEvidence, uint256 submittedAt, uint256 deadline, bool isVerified, address verifiedBy, uint256 finalPrice, uint8 status, uint8 rejectReason, string rejectDescription, uint8 feedType, bool isInitialFeed))',
    'function getRequestStatus(uint256 requestId) view returns (uint8)',
    'function getRoleAdmin(bytes32 role) view returns (bytes32)',
    'function grantFeederRole(address feeder)',
    'function grantFeederRoleBatch(address[] feeders)',
    'function grantProtocolRole(address protocol)',
    'function grantRole(bytes32 role, address account)',
    'function hasRole(bytes32 role, address account) view returns (bool)',
    'function isExpired(uint256 requestId) view returns (bool)',
    'function markExpired(uint256 requestId)',
    'function modifyPrice(uint256 requestId, uint256 modifiedPrice, string reason)',
    'function nextRequestId() view returns (uint256)',
    'function orderVolumeRequests(uint256, uint256) view returns (uint256)',
    'function pause()',
    'function paused() view returns (bool)',
    'function rejectPrice(uint256 requestId, uint8 reason, string description)',
    'function renounceRole(bytes32 role, address callerConfirmation)',
    'function requests(uint256) view returns (uint256 requestId, uint256 orderId, address seller, uint256 suggestedPrice, string priceEvidence, uint256 submittedAt, uint256 deadline, bool isVerified, address verifiedBy, uint256 finalPrice, uint8 status, uint8 rejectReason, string rejectDescription, uint8 feedType, bool isInitialFeed)',
    'function revokeFeederRole(address feeder)',
    'function revokeRole(bytes32 role, address account)',
    'function setConfig(address _config)',
    'function setVerificationTimeout(uint256 timeout)',
    'function submitSuggestedPrice(uint256 orderId, uint256 suggestedPrice, string priceEvidence, uint8 feedType, bool isInitialFeed) returns (uint256 requestId)',
    'function supportsInterface(bytes4 interfaceId) view returns (bool)',
    'function unpause()',
    'function usdt() view returns (address)',
    'function verificationTimeout() view returns (uint256)',
    // Events
    'event Paused(address account)',
    'event PriceApproved(uint256 indexed requestId, address indexed feeder, uint256 finalPrice, uint256 timestamp)',
    'event PriceModified(uint256 indexed requestId, address indexed feeder, uint256 originalPrice, uint256 modifiedPrice, string reason, uint256 timestamp)',
    'event PriceRejected(uint256 indexed requestId, address indexed feeder, uint8 reason, string description, uint256 timestamp)',
    'event RefeedRequired(uint256 indexed requestId, uint256 indexed orderId, string reason, uint256 timestamp)',
    'event RequestExpired(uint256 indexed requestId, uint256 timestamp)',
    'event RoleAdminChanged(bytes32 indexed role, bytes32 indexed previousAdminRole, bytes32 indexed newAdminRole)',
    'event RoleGranted(bytes32 indexed role, address indexed account, address indexed sender)',
    'event RoleRevoked(bytes32 indexed role, address indexed account, address indexed sender)',
    'event SuggestedPriceSubmitted(uint256 indexed requestId, uint256 indexed orderId, address indexed seller, uint256 suggestedPrice, string priceEvidence, uint8 feedType, uint256 timestamp)',
    'event Unpaused(address account)',
] as const;

// ERC20 ABI (for USDT)
export const ERC20ABI = [
    'function name() view returns (string)',
    'function symbol() view returns (string)',
    'function decimals() view returns (uint8)',
    'function totalSupply() view returns (uint256)',
    'function balanceOf(address account) view returns (uint256)',
    'function allowance(address owner, address spender) view returns (uint256)',
    'function approve(address spender, uint256 amount) returns (bool)',
    'function transfer(address to, uint256 amount) returns (bool)',
    'function transferFrom(address from, address to, uint256 amount) returns (bool)',
    'event Transfer(address indexed from, address indexed to, uint256 value)',
    'event Approval(address indexed owner, address indexed spender, uint256 value)',
] as const;
