/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export type UserPointsStruct = {
  totalPoints: BigNumberish;
  claimedPoints: BigNumberish;
  availablePoints: BigNumberish;
  lastUpdateTime: BigNumberish;
};

export type UserPointsStructOutput = [
  totalPoints: bigint,
  claimedPoints: bigint,
  availablePoints: bigint,
  lastUpdateTime: bigint
] & {
  totalPoints: bigint;
  claimedPoints: bigint;
  availablePoints: bigint;
  lastUpdateTime: bigint;
};

export declare namespace PointsManager {
  export type AirdropConfigStruct = {
    totalPool: BigNumberish;
    startTime: BigNumberish;
    endTime: BigNumberish;
    totalPointsSnapshot: BigNumberish;
    isActive: boolean;
    airdropId: BigNumberish;
  };

  export type AirdropConfigStructOutput = [
    totalPool: bigint,
    startTime: bigint,
    endTime: bigint,
    totalPointsSnapshot: bigint,
    isActive: boolean,
    airdropId: bigint
  ] & {
    totalPool: bigint;
    startTime: bigint;
    endTime: bigint;
    totalPointsSnapshot: bigint;
    isActive: boolean;
    airdropId: bigint;
  };
}

export interface PointsManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "AIRDROP_ADMIN_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "POINTS_OPERATOR_ROLE"
      | "airdropCounter"
      | "claimAirdrop"
      | "claimedAmount"
      | "config"
      | "createAirdrop"
      | "currentAirdrop"
      | "endAirdrop"
      | "getClaimableAirdrop"
      | "getCurrentAirdrop"
      | "getPoints"
      | "getPointsUserCount"
      | "getRoleAdmin"
      | "getUserPoints"
      | "grantOperatorRole"
      | "grantRole"
      | "hasClaimed"
      | "hasClaimedAirdrop"
      | "hasRole"
      | "nstToken"
      | "pause"
      | "paused"
      | "pointsUsers"
      | "recordPoints"
      | "renounceRole"
      | "revokeRole"
      | "setConfig"
      | "setNSTToken"
      | "supportsInterface"
      | "totalClaimedPoints"
      | "totalPoints"
      | "unpause"
      | "userPoints"
      | "withdrawRemainingTokens"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AirdropClaimed"
      | "AirdropCreated"
      | "AirdropEnded"
      | "Paused"
      | "PointsAccumulated"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "AIRDROP_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "POINTS_OPERATOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "airdropCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimAirdrop",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimedAmount",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "config", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "createAirdrop",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "currentAirdrop",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "endAirdrop",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getClaimableAirdrop",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentAirdrop",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPoints",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPointsUserCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserPoints",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantOperatorRole",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasClaimed",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasClaimedAirdrop",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "nstToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pointsUsers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordPoints",
    values: [AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setConfig",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setNSTToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalClaimedPoints",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalPoints",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "userPoints",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawRemainingTokens",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "AIRDROP_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "POINTS_OPERATOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "airdropCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimAirdrop",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimedAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "config", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createAirdrop",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentAirdrop",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "endAirdrop", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getClaimableAirdrop",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentAirdrop",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPoints", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPointsUserCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserPoints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantOperatorRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasClaimed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasClaimedAirdrop",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nstToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pointsUsers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordPoints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setConfig", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setNSTToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalClaimedPoints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalPoints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "userPoints", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawRemainingTokens",
    data: BytesLike
  ): Result;
}

export namespace AirdropClaimedEvent {
  export type InputTuple = [
    user: AddressLike,
    airdropId: BigNumberish,
    pointsUsed: BigNumberish,
    tokenAmount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    airdropId: bigint,
    pointsUsed: bigint,
    tokenAmount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    airdropId: bigint;
    pointsUsed: bigint;
    tokenAmount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AirdropCreatedEvent {
  export type InputTuple = [
    airdropId: BigNumberish,
    totalPool: BigNumberish,
    startTime: BigNumberish,
    endTime: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    airdropId: bigint,
    totalPool: bigint,
    startTime: bigint,
    endTime: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    airdropId: bigint;
    totalPool: bigint;
    startTime: bigint;
    endTime: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AirdropEndedEvent {
  export type InputTuple = [
    airdropId: BigNumberish,
    totalClaimed: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    airdropId: bigint,
    totalClaimed: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    airdropId: bigint;
    totalClaimed: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PointsAccumulatedEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    feeType: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    amount: bigint,
    feeType: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    amount: bigint;
    feeType: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PointsManager extends BaseContract {
  connect(runner?: ContractRunner | null): PointsManager;
  waitForDeployment(): Promise<this>;

  interface: PointsManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  AIRDROP_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  POINTS_OPERATOR_ROLE: TypedContractMethod<[], [string], "view">;

  airdropCounter: TypedContractMethod<[], [bigint], "view">;

  claimAirdrop: TypedContractMethod<[], [void], "nonpayable">;

  claimedAmount: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  config: TypedContractMethod<[], [string], "view">;

  createAirdrop: TypedContractMethod<
    [totalPool: BigNumberish, startTime: BigNumberish, endTime: BigNumberish],
    [void],
    "nonpayable"
  >;

  currentAirdrop: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, boolean, bigint] & {
        totalPool: bigint;
        startTime: bigint;
        endTime: bigint;
        totalPointsSnapshot: bigint;
        isActive: boolean;
        airdropId: bigint;
      }
    ],
    "view"
  >;

  endAirdrop: TypedContractMethod<[], [void], "nonpayable">;

  getClaimableAirdrop: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  getCurrentAirdrop: TypedContractMethod<
    [],
    [PointsManager.AirdropConfigStructOutput],
    "view"
  >;

  getPoints: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getPointsUserCount: TypedContractMethod<[], [bigint], "view">;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getUserPoints: TypedContractMethod<
    [user: AddressLike],
    [UserPointsStructOutput],
    "view"
  >;

  grantOperatorRole: TypedContractMethod<
    [operator: AddressLike],
    [void],
    "nonpayable"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasClaimed: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  hasClaimedAirdrop: TypedContractMethod<
    [airdropId: BigNumberish, user: AddressLike],
    [boolean],
    "view"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  nstToken: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  pointsUsers: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  recordPoints: TypedContractMethod<
    [user: AddressLike, feeAmount: BigNumberish, feeType: string],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setConfig: TypedContractMethod<[_config: AddressLike], [void], "nonpayable">;

  setNSTToken: TypedContractMethod<
    [_nstToken: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  totalClaimedPoints: TypedContractMethod<[], [bigint], "view">;

  totalPoints: TypedContractMethod<[], [bigint], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  userPoints: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint] & {
        totalPoints: bigint;
        claimedPoints: bigint;
        availablePoints: bigint;
        lastUpdateTime: bigint;
      }
    ],
    "view"
  >;

  withdrawRemainingTokens: TypedContractMethod<
    [to: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "AIRDROP_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "POINTS_OPERATOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "airdropCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "claimAirdrop"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimedAmount"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "config"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createAirdrop"
  ): TypedContractMethod<
    [totalPool: BigNumberish, startTime: BigNumberish, endTime: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "currentAirdrop"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, boolean, bigint] & {
        totalPool: bigint;
        startTime: bigint;
        endTime: bigint;
        totalPointsSnapshot: bigint;
        isActive: boolean;
        airdropId: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "endAirdrop"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getClaimableAirdrop"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCurrentAirdrop"
  ): TypedContractMethod<[], [PointsManager.AirdropConfigStructOutput], "view">;
  getFunction(
    nameOrSignature: "getPoints"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPointsUserCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getUserPoints"
  ): TypedContractMethod<[user: AddressLike], [UserPointsStructOutput], "view">;
  getFunction(
    nameOrSignature: "grantOperatorRole"
  ): TypedContractMethod<[operator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasClaimed"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasClaimedAirdrop"
  ): TypedContractMethod<
    [airdropId: BigNumberish, user: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "nstToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pointsUsers"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "recordPoints"
  ): TypedContractMethod<
    [user: AddressLike, feeAmount: BigNumberish, feeType: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setConfig"
  ): TypedContractMethod<[_config: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setNSTToken"
  ): TypedContractMethod<[_nstToken: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "totalClaimedPoints"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalPoints"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userPoints"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint] & {
        totalPoints: bigint;
        claimedPoints: bigint;
        availablePoints: bigint;
        lastUpdateTime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdrawRemainingTokens"
  ): TypedContractMethod<[to: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AirdropClaimed"
  ): TypedContractEvent<
    AirdropClaimedEvent.InputTuple,
    AirdropClaimedEvent.OutputTuple,
    AirdropClaimedEvent.OutputObject
  >;
  getEvent(
    key: "AirdropCreated"
  ): TypedContractEvent<
    AirdropCreatedEvent.InputTuple,
    AirdropCreatedEvent.OutputTuple,
    AirdropCreatedEvent.OutputObject
  >;
  getEvent(
    key: "AirdropEnded"
  ): TypedContractEvent<
    AirdropEndedEvent.InputTuple,
    AirdropEndedEvent.OutputTuple,
    AirdropEndedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PointsAccumulated"
  ): TypedContractEvent<
    PointsAccumulatedEvent.InputTuple,
    PointsAccumulatedEvent.OutputTuple,
    PointsAccumulatedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "AirdropClaimed(address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      AirdropClaimedEvent.InputTuple,
      AirdropClaimedEvent.OutputTuple,
      AirdropClaimedEvent.OutputObject
    >;
    AirdropClaimed: TypedContractEvent<
      AirdropClaimedEvent.InputTuple,
      AirdropClaimedEvent.OutputTuple,
      AirdropClaimedEvent.OutputObject
    >;

    "AirdropCreated(uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      AirdropCreatedEvent.InputTuple,
      AirdropCreatedEvent.OutputTuple,
      AirdropCreatedEvent.OutputObject
    >;
    AirdropCreated: TypedContractEvent<
      AirdropCreatedEvent.InputTuple,
      AirdropCreatedEvent.OutputTuple,
      AirdropCreatedEvent.OutputObject
    >;

    "AirdropEnded(uint256,uint256,uint256)": TypedContractEvent<
      AirdropEndedEvent.InputTuple,
      AirdropEndedEvent.OutputTuple,
      AirdropEndedEvent.OutputObject
    >;
    AirdropEnded: TypedContractEvent<
      AirdropEndedEvent.InputTuple,
      AirdropEndedEvent.OutputTuple,
      AirdropEndedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PointsAccumulated(address,uint256,string,uint256)": TypedContractEvent<
      PointsAccumulatedEvent.InputTuple,
      PointsAccumulatedEvent.OutputTuple,
      PointsAccumulatedEvent.OutputObject
    >;
    PointsAccumulated: TypedContractEvent<
      PointsAccumulatedEvent.InputTuple,
      PointsAccumulatedEvent.OutputTuple,
      PointsAccumulatedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
