/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IOptionsCore,
  IOptionsCoreInterface,
} from "../../../contracts/interfaces/IOptionsCore";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "orderId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "string",
        name: "underlyingCode",
        type: "string",
      },
      {
        indexed: false,
        internalType: "string",
        name: "market",
        type: "string",
      },
      {
        indexed: false,
        internalType: "string",
        name: "country",
        type: "string",
      },
      {
        indexed: false,
        internalType: "enum FeedType",
        name: "feedType",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "enum FeedTier",
        name: "tier",
        type: "uint8",
      },
      {
        indexed: true,
        internalType: "address",
        name: "requester",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "notionalAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "FeedRequestEmitted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "orderId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "string",
        name: "reason",
        type: "string",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "OrderCancelled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "orderId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "creator",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "isBuyerOrder",
        type: "bool",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "OrderCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "orderId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "buyer",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "seller",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "OrderMatched",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "orderId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "enum OrderStatus",
        name: "oldStatus",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "enum OrderStatus",
        name: "newStatus",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "string",
        name: "reason",
        type: "string",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "OrderStatusChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "orderId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "quoteId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "seller",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "QuoteMarginRefunded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "orderId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "quoteId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "seller",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "premiumRate",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "QuoteSubmitted",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "quoteId",
        type: "uint256",
      },
    ],
    name: "acceptQuote",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "orderId",
        type: "uint256",
      },
    ],
    name: "cancelRFQ",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "underlyingName",
        type: "string",
      },
      {
        internalType: "string",
        name: "underlyingCode",
        type: "string",
      },
      {
        internalType: "string",
        name: "market",
        type: "string",
      },
      {
        internalType: "string",
        name: "country",
        type: "string",
      },
      {
        internalType: "string",
        name: "refPrice",
        type: "string",
      },
      {
        internalType: "enum Direction",
        name: "direction",
        type: "uint8",
      },
      {
        internalType: "uint256",
        name: "notionalUSDT",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "expiryTimestamp",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "maxPremiumRate",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "minMarginRate",
        type: "uint256",
      },
      {
        internalType: "enum SellerType",
        name: "acceptedSellerType",
        type: "uint8",
      },
      {
        internalType: "address",
        name: "designatedSeller",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "arbitrationWindow",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "marginCallDeadline",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "dividendAdjustment",
        type: "bool",
      },
      {
        internalType: "enum LiquidationRule",
        name: "liquidationRule",
        type: "uint8",
      },
      {
        internalType: "uint8",
        name: "consecutiveDays",
        type: "uint8",
      },
      {
        internalType: "uint8",
        name: "dailyLimitPercent",
        type: "uint8",
      },
      {
        internalType: "enum FeedRule",
        name: "feedRule",
        type: "uint8",
      },
    ],
    name: "createBuyerRFQ",
    outputs: [
      {
        internalType: "uint256",
        name: "orderId",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "underlyingName",
        type: "string",
      },
      {
        internalType: "string",
        name: "underlyingCode",
        type: "string",
      },
      {
        internalType: "string",
        name: "market",
        type: "string",
      },
      {
        internalType: "string",
        name: "country",
        type: "string",
      },
      {
        internalType: "string",
        name: "refPrice",
        type: "string",
      },
      {
        internalType: "enum Direction",
        name: "direction",
        type: "uint8",
      },
      {
        internalType: "uint256",
        name: "notionalUSDT",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "expiryTimestamp",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "premiumRate",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "marginAmount",
        type: "uint256",
      },
      {
        internalType: "enum LiquidationRule",
        name: "liquidationRule",
        type: "uint8",
      },
      {
        internalType: "uint8",
        name: "consecutiveDays",
        type: "uint8",
      },
      {
        internalType: "uint8",
        name: "dailyLimitPercent",
        type: "uint8",
      },
      {
        internalType: "uint256",
        name: "arbitrationWindow",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "dividendAdjustment",
        type: "bool",
      },
      {
        internalType: "uint8",
        name: "exerciseDelay",
        type: "uint8",
      },
      {
        internalType: "enum FeedRule",
        name: "feedRule",
        type: "uint8",
      },
    ],
    name: "createSellerOrder",
    outputs: [
      {
        internalType: "uint256",
        name: "orderId",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "buyer",
        type: "address",
      },
    ],
    name: "getBuyerOrders",
    outputs: [
      {
        internalType: "uint256[]",
        name: "",
        type: "uint256[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "orderId",
        type: "uint256",
      },
    ],
    name: "getOrder",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "orderId",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "buyer",
            type: "address",
          },
          {
            internalType: "address",
            name: "seller",
            type: "address",
          },
          {
            internalType: "string",
            name: "underlyingName",
            type: "string",
          },
          {
            internalType: "string",
            name: "underlyingCode",
            type: "string",
          },
          {
            internalType: "string",
            name: "market",
            type: "string",
          },
          {
            internalType: "string",
            name: "country",
            type: "string",
          },
          {
            internalType: "string",
            name: "refPrice",
            type: "string",
          },
          {
            internalType: "enum Direction",
            name: "direction",
            type: "uint8",
          },
          {
            internalType: "uint256",
            name: "notionalUSDT",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "strikePrice",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "expiryTimestamp",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "premiumRate",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "premiumAmount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "initialMargin",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "currentMargin",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "minMarginRate",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "maxPremiumRate",
            type: "uint256",
          },
          {
            internalType: "enum LiquidationRule",
            name: "liquidationRule",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "consecutiveDays",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "dailyLimitPercent",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "exerciseDelay",
            type: "uint8",
          },
          {
            internalType: "enum SellerType",
            name: "sellerType",
            type: "uint8",
          },
          {
            internalType: "address",
            name: "designatedSeller",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "arbitrationWindow",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "marginCallDeadline",
            type: "uint256",
          },
          {
            internalType: "bool",
            name: "dividendAdjustment",
            type: "bool",
          },
          {
            internalType: "enum FeedRule",
            name: "feedRule",
            type: "uint8",
          },
          {
            internalType: "enum OrderStatus",
            name: "status",
            type: "uint8",
          },
          {
            internalType: "uint256",
            name: "createdAt",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "matchedAt",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "settledAt",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "finalFeedRequestedAt",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "lastFeedPrice",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "dividendAmount",
            type: "uint256",
          },
        ],
        internalType: "struct Order",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "orderId",
        type: "uint256",
      },
    ],
    name: "getQuotes",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "quoteId",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "orderId",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "seller",
            type: "address",
          },
          {
            internalType: "enum SellerType",
            name: "sellerType",
            type: "uint8",
          },
          {
            internalType: "uint256",
            name: "premiumRate",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "premiumAmount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "marginRate",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "marginAmount",
            type: "uint256",
          },
          {
            internalType: "enum LiquidationRule",
            name: "liquidationRule",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "consecutiveDays",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "dailyLimitPercent",
            type: "uint8",
          },
          {
            internalType: "uint256",
            name: "createdAt",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "expiresAt",
            type: "uint256",
          },
          {
            internalType: "enum QuoteStatus",
            name: "status",
            type: "uint8",
          },
        ],
        internalType: "struct Quote[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "seller",
        type: "address",
      },
    ],
    name: "getSellerOrders",
    outputs: [
      {
        internalType: "uint256[]",
        name: "",
        type: "uint256[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "orderId",
        type: "uint256",
      },
      {
        internalType: "enum FeedType",
        name: "feedType",
        type: "uint8",
      },
    ],
    name: "onFeedRequested",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "orderId",
        type: "uint256",
      },
      {
        internalType: "enum FeedType",
        name: "feedType",
        type: "uint8",
      },
      {
        internalType: "uint256",
        name: "finalPrice",
        type: "uint256",
      },
    ],
    name: "processFeedCallback",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "orderId",
        type: "uint256",
      },
      {
        internalType: "enum FeedTier",
        name: "tier",
        type: "uint8",
      },
    ],
    name: "requestFeed",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "orderId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "premiumRate",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "marginRate",
        type: "uint256",
      },
      {
        internalType: "enum LiquidationRule",
        name: "liquidationRule",
        type: "uint8",
      },
      {
        internalType: "uint8",
        name: "consecutiveDays",
        type: "uint8",
      },
      {
        internalType: "uint8",
        name: "dailyLimitPercent",
        type: "uint8",
      },
    ],
    name: "submitQuote",
    outputs: [
      {
        internalType: "uint256",
        name: "quoteId",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IOptionsCore__factory {
  static readonly abi = _abi;
  static createInterface(): IOptionsCoreInterface {
    return new Interface(_abi) as IOptionsCoreInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IOptionsCore {
    return new Contract(address, _abi, runner) as unknown as IOptionsCore;
  }
}
